site_name: Tristan Reynders
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - content.code.annotate
    - search.share
    - search.suggest
    - content.tabs.link
    - announce.dismiss  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue grey
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: blue grey
      accent: light blue

plugins:
  - social
  - material/search
  - tags

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.details
  - extra
  - smarty
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: false
  social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/tristan-reynders
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/in/tristanreynders
